# Generated by Django 4.1.3 on 2022-11-22 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                ("archetype", models.TextField(max_length=200)),
                ("background", models.TextField(blank=True, max_length=200, null=True)),
                ("armor", models.SmallIntegerField(blank=True, default=0, null=True)),
                ("hp", models.SmallIntegerField(blank=True, default=0, null=True)),
                (
                    "current_hp",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                ("body", models.SmallIntegerField(blank=True, default=0, null=True)),
                ("mind", models.SmallIntegerField(blank=True, default=0, null=True)),
                ("luck", models.SmallIntegerField(blank=True, default=0, null=True)),
                ("gear", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
