# Generated by Django 4.1.3 on 2022-11-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="origin",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
