# Generated by Django 4.1.3 on 2022-11-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_character_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="gold",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
