# Generated by Django 4.1.3 on 2022-11-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_character_gold"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="abilities",
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
