# Generated by Django 4.1.3 on 2022-11-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("hp", models.IntegerField()),
                ("body", models.IntegerField()),
                ("mind", models.IntegerField()),
                ("armor", models.IntegerField(blank=True, null=True)),
                ("attack", models.CharField(blank=True, max_length=60)),
                ("special", models.TextField(blank=True)),
            ],
        ),
    ]
